### ISSUE TITLE
Coding style C

### ISSUE THREAD

**Issue by lebrunthibault** [cloudnodes/coding-style#1]
Salut !

Bonne idée l'utilisation de clang-format ! Je suis à l'EPITA en 1ère année aussi et on est plusieurs à chercher une solution pour la coding style :p
Tu l'utilises que pour le C++ ? 
J'ai testé pour le C et il faut enlever quelques trucs comme :

`IndentPPDirectives: AfterHash`

Aussi il y avait un ou deux trucs qui me semblaient pas respecter la coding style C genre
`BinPackParameters: true` pour que la parenthèse ouvrante n'ait pas d'espace après quand on déclare une fonction. Bref.

du coup j'ai créé un autre .clang-format pour le C, si tu veux on peut le rajouter à ton repo et mettre l'un dans un dossier cpp et l'autre c ou les nommer différement.

Si çà t'intéresse je peux te faire une pr !
A toute

Thibault Lebrun

**Comment by antoinedray** [comment]
Hello !

Mille excuse pour cette réponse plus que tardive.

Ce serait avec plaisir de push tes modifications si tu en as.

Cordialement,

Antoine
